openapi: 3.0.1
info:
  title: httpbin.org
  description: "A simple HTTP Request & Response Service.<br/> <br/> <b>Run locally:\
    \ </b> <code>$ docker run -p 80:80 kennethreitz/httpbin</code>"
  contact:
    url: https://kennethreitz.org
    email: me@kennethreitz.org
  version: 0.9.2-42CrunchSubset
servers:
- url: http://localhost:8080/
tags:
- name: Request inspection
  description: Inspect the request data
- name: Dynamic data
  description: Generates random and dynamic data
- name: AI
  description: Leverage AI to transform and validate data
paths:
  /base64/decode/{value}:
    post:
      tags:
      - Dynamic data
      summary: Decodes base64url-encoded string.
      parameters:
      - name: value
        in: path
        required: true
        schema:
          maxLength: 500
          pattern: "^[0-9a-zA-Z=]+$"
          type: string
          default: QmFsbGVyaW5hIGlzIGF3ZXNvbWUh
      responses:
        "200":
          description: Decoded base64 content.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/base64_response' 
  /base64/encode/{value}:
    post:
      tags:
      - Dynamic data
      summary: Decodes base64url-encoded string.
      parameters:
      - name: value
        in: path
        required: true
        schema:
          maxLength: 500
          pattern: "^[0-9a-zA-Z\\s!$-_]+$"
          type: string
          default: "Ballerina is awesome!"
      responses:
        "200":
          description: Decoded base64 content.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/base64_response'        
  /ip:
    get:
      tags:
      - Request inspection
      summary: Returns the requester's IP Address.
      responses:
        "200":
          description: The Requester's IP Address.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ip_response'
  /user-agent:
    get:
      tags:
      - Request inspection
      summary: Return the incoming requests's User-Agent header.
      responses:
        "200":
          description: The request's User-Agent header.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ua_response'
  /uuid:
    get:
      tags:
      - Dynamic data
      summary: Return a UUID4.
      responses:
        "200":
          description: A UUID4.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/uuid_response'

components:
  schemas:
    ip_response:
      type: object
      additionalProperties: false
      properties:
        origin:
          maxLength: 64
          pattern: "^[0-9\\.]+$"
          type: string
    base64_response:
      type: object
      additionalProperties: false
      properties:
        value:
          maxLength: 100
          pattern: "^[0-9\\.]+$"
          type: string
    ua_response:
      type: object
      additionalProperties: false
      properties:
        user-agent:
          maxLength: 1000
          pattern: "^[0-9a-zA-Z_\\-\\/,();\\.\\s]+$"
          type: string
    uuid_response:
      type: object
      additionalProperties: false
      properties:
        uuid:
          maxLength: 36
          minLength: 36
          pattern: "^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$"
          type: string
